create table if not exists public.deck_cache (
  id bigint generated by default as identity primary key,
  topic text not null,
  topic_key text not null,
  deck_name text not null,
  tags jsonb not null default '[]'::jsonb,
  cards jsonb not null,
  word_lang text not null default 'technical',
  def_lang text not null,
  detail_level integer not null default 2,
  created_by_user_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists deck_cache_topic_key_def_lang_idx
  on public.deck_cache (topic_key, def_lang);

create table if not exists public.daily_generate_usage (
  id bigint generated by default as identity primary key,
  user_id text not null,
  usage_date date not null,
  count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists daily_generate_usage_user_date_idx
  on public.daily_generate_usage (user_id, usage_date);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists deck_cache_set_updated_at on public.deck_cache;
create trigger deck_cache_set_updated_at
before update on public.deck_cache
for each row execute function public.set_updated_at();

drop trigger if exists daily_generate_usage_set_updated_at on public.daily_generate_usage;
create trigger daily_generate_usage_set_updated_at
before update on public.daily_generate_usage
for each row execute function public.set_updated_at();
