export const SEED_DECKS = [
  {
    id: "seed-1",
    name: "IT基礎",
    author: "サンプル",
    isPublic: true,
    wordLang: "technical",
    defLang: "ja",
    detailLevel: 2,
    tags: ["#IT", "#基礎", "#プログラミング"],
    cleared: false,
    masteredIds: [],
    favorited: false,
    favCount: 12,
    cards: [
      { id: "s1a", word: "CPU", definition: "計算や命令の実行を担当するコンピュータの中核部品。Central Processing Unitの略。" },
      { id: "s1b", word: "RAM", definition: "作業中のデータを一時的に保存するメモリ。電源を切ると内容は消える。" },
      { id: "s1c", word: "Algorithm", definition: "問題を解くための手順・規則のまとまり。プログラムの処理方法を定義する概念。" },
      { id: "s1d", word: "API", definition: "ソフトウェア同士が機能やデータをやり取りするための接続規約。" },
    ],
  },
  {
    id: "seed-2",
    name: "英語上級",
    author: "サンプル",
    isPublic: true,
    wordLang: "en",
    defLang: "ja",
    detailLevel: 2,
    tags: ["#英語", "#単語", "#TOEFL"],
    cleared: false,
    masteredIds: [],
    favorited: false,
    favCount: 8,
    cards: [
      { id: "s2a", word: "ephemeral", definition: "ごく短い時間しか続かないさま。一時的・はかないことを指す形容詞。" },
      { id: "s2b", word: "ubiquitous", definition: "どこにでも存在し、非常に広く見られる状態。遍在する。" },
      { id: "s2c", word: "paradigm", definition: "物事の見方や考え方の枠組み。ある時代・分野における支配的な思考モデル。" },
      { id: "s2d", word: "resilience", definition: "困難や失敗から立ち直る力。回復力・復元力を指す。" },
    ],
  },
  {
    id: "seed-3",
    name: "科学用語",
    author: "サンプル",
    isPublic: true,
    wordLang: "technical",
    defLang: "ja",
    detailLevel: 2,
    tags: ["#科学", "#基礎", "#学習"],
    cleared: false,
    masteredIds: [],
    favorited: false,
    favCount: 5,
    cards: [
      { id: "s3a", word: "Hypothesis", definition: "観察や実験によって検証すべき仮説。科学的探究の出発点となる命題。" },
      { id: "s3b", word: "Variable", definition: "変化しうる値や条件を表す要素。数式やプログラムで変動する量を指す。" },
      { id: "s3c", word: "Observation", definition: "対象を注意深く見て事実や変化を記録する行為。科学的手法の基本ステップ。" },
    ],
  },
];

export const SAMPLE_CARD_DEFINITIONS = Object.fromEntries(
  SEED_DECKS.flatMap((deck) => deck.cards.map((card) => [card.id, card.definition])),
);
