export const SEED_DECKS = [
  {
    id: "seed-1",
    name: "IT基礎",
    author: "サンプル",
    isPublic: true,
    wordLang: "technical",
    defLang: "ja",
    detailLevel: 2,
    tags: ["#IT", "#基礎", "#プログラミング"],
    cleared: false,
    masteredIds: [],
    favorited: false,
    favCount: 12,
    cards: [
      { id: "s1a", word: "CPU", definition: "計算や命令の実行を担当するコンピュータの中核部品。Central Processing Unitの略。" },
      { id: "s1b", word: "RAM", definition: "作業中のデータを一時的に保存するメモリ。電源を切ると内容は消える。" },
      { id: "s1c", word: "Algorithm", definition: "問題を解くための手順・規則のまとまり。プログラムの処理方法を定義する概念。" },
      { id: "s1d", word: "API", definition: "ソフトウェア同士が機能やデータをやり取りするための接続規約。" },
    ],
  },
  {
    id: "seed-2",
    name: "英語上級",
    author: "サンプル",
    isPublic: true,
    wordLang: "en",
    defLang: "ja",
    detailLevel: 2,
    tags: ["#英語", "#単語", "#TOEFL"],
    cleared: false,
    masteredIds: [],
    favorited: false,
    favCount: 8,
    cards: [
      { id: "s2a", word: "ephemeral", definition: "ごく短い時間しか続かないさま。一時的・はかないことを指す形容詞。" },
      { id: "s2b", word: "ubiquitous", definition: "どこにでも存在し、非常に広く見られる状態。遍在する。" },
      { id: "s2c", word: "paradigm", definition: "物事の見方や考え方の枠組み。ある時代・分野における支配的な思考モデル。" },
      { id: "s2d", word: "resilience", definition: "困難や失敗から立ち直る力。回復力・復元力を指す。" },
    ],
  },
  {
    id: "seed-3",
    name: "科学用語",
    author: "サンプル",
    isPublic: true,
    wordLang: "technical",
    defLang: "ja",
    detailLevel: 2,
    tags: ["#科学", "#基礎", "#学習"],
    cleared: false,
    masteredIds: [],
    favorited: false,
    favCount: 5,
    cards: [
      { id: "s3a", word: "Hypothesis", definition: "観察や実験によって検証すべき仮説。科学的探究の出発点となる命題。" },
      { id: "s3b", word: "Variable", definition: "変化しうる値や条件を表す要素。数式やプログラムで変動する量を指す。" },
      { id: "s3c", word: "Observation", definition: "対象を注意深く見て事実や変化を記録する行為。科学的手法の基本ステップ。" },
    ],
  },
  {
    id: "seed-4",
    name: "日常英会話",
    author: "サンプル",
    isPublic: true,
    wordLang: "en",
    defLang: "ja",
    detailLevel: 2,
    tags: ["#英語", "#英会話", "#日常"],
    cleared: false,
    masteredIds: [],
    favorited: false,
    favCount: 15,
    cards: [
      { id: "s4a", word: "How's it going?", definition: "「調子どう？」というカジュアルな挨拶。友人同士でよく使う。" },
      { id: "s4b", word: "I'm on my way.", definition: "「今向かってるよ」。待ち合わせのときなどに使う定番フレーズ。" },
      { id: "s4c", word: "It's up to you.", definition: "「あなた次第だよ」「任せるよ」。相手に判断をゆだねるときの表現。" },
      { id: "s4d", word: "That makes sense.", definition: "「なるほど、わかる」。相手の説明に納得したときに使う相づち。" },
      { id: "s4e", word: "Let me sleep on it.", definition: "「一晩考えさせて」。すぐに決められないときに使う表現。" },
    ],
  },
  {
    id: "seed-5",
    name: "心理学入門",
    author: "サンプル",
    isPublic: true,
    wordLang: "technical",
    defLang: "ja",
    detailLevel: 2,
    tags: ["#心理学", "#入門", "#教養"],
    cleared: false,
    masteredIds: [],
    favorited: false,
    favCount: 9,
    cards: [
      { id: "s5a", word: "認知バイアス", definition: "思い込みや偏りによって判断がゆがむ心理現象。誰にでも起こりうる脳のクセ。" },
      { id: "s5b", word: "マズローの欲求階層", definition: "人間の欲求を5段階に分けた理論。生理的欲求から自己実現欲求まで順に高くなる。" },
      { id: "s5c", word: "確証バイアス", definition: "自分の信じたいことを裏付ける情報ばかり集めてしまう傾向。" },
      { id: "s5d", word: "プラシーボ効果", definition: "偽の薬でも「効く」と信じることで実際に症状が改善する現象。思い込みの力。" },
    ],
  },
  {
    id: "seed-6",
    name: "ビジネス用語",
    author: "サンプル",
    isPublic: true,
    wordLang: "technical",
    defLang: "ja",
    detailLevel: 2,
    tags: ["#ビジネス", "#仕事", "#社会人"],
    cleared: false,
    masteredIds: [],
    favorited: false,
    favCount: 11,
    cards: [
      { id: "s6a", word: "KPI", definition: "目標の達成度を測るための数値指標。Key Performance Indicatorの略。" },
      { id: "s6b", word: "ROI", definition: "投資に対してどれだけ利益が出たかを示す指標。費用対効果のこと。" },
      { id: "s6c", word: "PDCA", definition: "Plan→Do→Check→Actの4ステップを繰り返して業務を改善する手法。" },
      { id: "s6d", word: "ステークホルダー", definition: "事業やプロジェクトに利害関係を持つ人や組織。顧客・株主・従業員など。" },
      { id: "s6e", word: "リードタイム", definition: "作業の開始から完了までにかかる時間。短いほど効率が良いとされる。" },
    ],
  },
  {
    id: "seed-7",
    name: "日本史キーワード",
    author: "サンプル",
    isPublic: true,
    wordLang: "ja",
    defLang: "ja",
    detailLevel: 2,
    tags: ["#日本史", "#歴史", "#受験"],
    cleared: false,
    masteredIds: [],
    favorited: false,
    favCount: 7,
    cards: [
      { id: "s7a", word: "大化の改新", definition: "645年に中大兄皇子らが蘇我氏を倒し、天皇中心の国づくりを始めた政治改革。" },
      { id: "s7b", word: "鎖国", definition: "江戸幕府が外国との交流を厳しく制限した政策。約200年間続いた。" },
      { id: "s7c", word: "明治維新", definition: "1868年から始まった日本の近代化改革。武士の時代が終わり、西洋の制度を導入した。" },
      { id: "s7d", word: "廃藩置県", definition: "明治政府が藩を廃止して県を置いた政策。中央集権体制を確立するための改革。" },
    ],
  },
  {
    id: "seed-8",
    name: "プログラミング基礎",
    author: "サンプル",
    isPublic: true,
    wordLang: "technical",
    defLang: "ja",
    detailLevel: 2,
    tags: ["#プログラミング", "#初心者", "#コード"],
    cleared: false,
    masteredIds: [],
    favorited: false,
    favCount: 10,
    cards: [
      { id: "s8a", word: "変数", definition: "データを入れておく名前付きの箱。プログラムの中で値を保存・変更するために使う。" },
      { id: "s8b", word: "関数", definition: "まとまった処理に名前をつけて再利用できるようにしたもの。入力を受け取り結果を返す。" },
      { id: "s8c", word: "ループ", definition: "同じ処理を条件が満たされるまで繰り返す仕組み。for文やwhile文が代表的。" },
      { id: "s8d", word: "配列", definition: "複数のデータをまとめて順番に管理するデータ構造。番号（インデックス）でアクセスする。" },
      { id: "s8e", word: "条件分岐", definition: "条件に応じて処理を切り替える仕組み。if文が代表的。「もし〇〇なら△△する」。" },
    ],
  },
  {
    id: "seed-9",
    name: "Windowsショートカットキー",
    author: "サンプル",
    isPublic: true,
    wordLang: "technical",
    defLang: "ja",
    detailLevel: 2,
    tags: ["#Windows", "#ショートカット", "#PC操作"],
    cleared: false,
    masteredIds: [],
    favorited: false,
    favCount: 14,
    cards: [
      { id: "s9a", word: "Ctrl + C / Ctrl + V", definition: "コピー＆貼り付け。選択したものを複製して別の場所に貼る、最も基本の操作。" },
      { id: "s9b", word: "Ctrl + Z", definition: "元に戻す（Undo）。直前の操作を取り消す。間違えたらとりあえずこれ。" },
      { id: "s9c", word: "Alt + Tab", definition: "開いているウィンドウを切り替える。複数のアプリを行き来するときに便利。" },
      { id: "s9d", word: "Win + D", definition: "デスクトップを一瞬で表示する。もう一度押すと元に戻る。" },
      { id: "s9e", word: "Win + L", definition: "画面をロックする。席を離れるときのセキュリティ対策に必須。" },
      { id: "s9f", word: "Ctrl + Shift + Esc", definition: "タスクマネージャーを直接開く。アプリが固まったときの強制終了に使う。" },
    ],
  },
];

export const SAMPLE_CARD_DEFINITIONS = Object.fromEntries(
  SEED_DECKS.flatMap((deck) => deck.cards.map((card) => [card.id, card.definition])),
);
