-- 毎朝メッセージ用: 日次目標/TODO保存テーブル
create table if not exists public.daily_goals (
  id bigint generated by default as identity primary key,
  goal_date date not null,
  goal text not null,
  todos jsonb not null default '[]'::jsonb,
  source text not null default 'ai',          -- 'saved' | 'ai' | 'fallback'
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 1日1レコードを保証
create unique index if not exists daily_goals_date_idx
  on public.daily_goals (goal_date);

-- updated_at 自動更新トリガー（既存の set_updated_at 関数を再利用）
drop trigger if exists daily_goals_set_updated_at on public.daily_goals;
create trigger daily_goals_set_updated_at
before update on public.daily_goals
for each row execute function public.set_updated_at();
