-- 公開ライブラリ用テーブル
create table if not exists public.public_decks (
  id bigint generated by default as identity primary key,
  deck_name text not null,
  author text not null default '匿名',
  word_lang text not null default 'en',
  def_lang text not null default 'ja',
  detail_level integer not null default 2,
  tags jsonb not null default '[]'::jsonb,
  cards jsonb not null,
  card_count integer not null default 0,
  save_count integer not null default 0,
  published_by text,
  source_deck_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 同一ユーザー・同一ソースデッキの重複投稿防止
create unique index if not exists public_decks_source_unique_idx
  on public.public_decks (published_by, source_deck_id)
  where published_by is not null and source_deck_id is not null;

-- 検索用インデックス
create index if not exists public_decks_created_at_idx
  on public.public_decks (created_at desc);

-- updated_atトリガー
drop trigger if exists public_decks_set_updated_at on public.public_decks;
create trigger public_decks_set_updated_at
before update on public.public_decks
for each row execute function public.set_updated_at();

-- save_countをアトミックに増減するRPC
create or replace function public.increment_save_count(deck_id bigint, delta integer)
returns integer
language plpgsql
as $$
declare
  new_count integer;
begin
  update public.public_decks
  set save_count = greatest(0, save_count + delta)
  where id = deck_id
  returning save_count into new_count;

  if not found then
    raise exception 'Deck not found';
  end if;

  return new_count;
end;
$$;
